import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import { useContext } from "react";
import { GlobalContext } from "../context/GlobalContext";

export default function Privacy() {
  const { theme } = useContext(GlobalContext);

  return (
    <div className={theme === "dark" ? "bg-black" : " bg-white"}>
      <Navbar />

      <div
        className={`max-w-4xl mx-auto px-6 py-12  ${
          theme === "dark" ? "text-black" : "text-gray-800"
        }`}
      >
        <h1 className="text-3xl font-bold mb-4">Privacy Policy</h1>
        <p
          className={`text-sm mb-8 ${
            theme === "dark" ? "text-gray-500" : "text-gray-600"
          }`}
        >
          Updated at June 10th, 2025
        </p>

        <div className="space-y-8">
          <div
            className={`leading-relaxed  ${
              theme === "dark" ? "text-gray-400" : "text-black"
            }`}
          >
            <p>
              BioYap ("we," "our," or "us") is committed to protecting your
              privacy. This Privacy Policy explains how your personal
              information is collected, used, and disclosed by BioYap.
            </p>
            <br />
            <p>
              This Privacy Policy applies to our website/app, and its associated
              subdomains (collectively, our "Service") alongside our
              application, BioYap. By accessing or using our Service, you
              signify that you have read, understood, and agree to our
              collection, storage, use, and disclosure of your personal
              information as described in this Privacy Policy and our Terms of
              Service.
            </p>
          </div>

          <Section title="Definitions and Key Terms">
            <div className="space-y-3">
              <div>
                <strong>Cookie:</strong> small amount of data generated by a
                website and saved by your web browser. It is used to identify
                your browser, provide analytics, remember information about you
                such as your language preference or login information.
              </div>
              <div>
                <strong>Company:</strong> when this policy mentions "Company,"
                "we," "us," or "our," it refers to BioYap LLC, (Tampa, Florida),
                that is responsible for your information under this Privacy
                Policy.
              </div>
              <div>
                <strong>Country:</strong> where BioYap or the owners/founders of
                BioYap are based, in this case is United States of America.
              </div>
              <div>
                <strong>Customer:</strong> refers to the company, organization
                or person that signs up to use the BioYap Service to manage the
                relationships with your consumers or service users.
              </div>
              <div>
                <strong>Device:</strong> any internet connected device such as a
                phone, tablet, computer or any other device that can be used to
                visit BioYap and use the services.
              </div>
              <div>
                <strong>IP address:</strong> Every device connected to the
                Internet is assigned a number known as an Internet protocol (IP)
                address. These numbers are usually assigned in geographic
                blocks. An IP address can often be used to identify the location
                from which a device is connecting to the Internet.
              </div>
              <div>
                <strong>Personnel:</strong> refers to those individuals who are
                employed by BioYap or are under contract to perform a service on
                behalf of one of the parties.
              </div>
              <div>
                <strong>Personal Data:</strong> any information that directly,
                indirectly, or in connection with other information — including
                a personal identification number — allows for the identification
                or identifiability of a natural person.
              </div>
              <div>
                <strong>Service:</strong> refers to the service provided by
                BioYap as described in the relative terms (if available) and on
                this platform.
              </div>
              <div>
                <strong>Third-party service:</strong> refers to advertisers,
                contest sponsors, promotional and marketing partners, and others
                who provide our content or whose products or services we think
                may interest you.
              </div>
              <div>
                <strong>You:</strong> a person or entity that is registered with
                BioYap to use the Services.
              </div>
            </div>
          </Section>

          <Section title="What Information Do We Collect?">
            <p>
              We collect information from you when you visit our website/app,
              register on our site, place an order, subscribe to our newsletter,
              respond to a survey or fill out a form.
            </p>
            <br />
            <div className="space-y-2">
              <div>• Name / Username</div>
              <div>• Phone Numbers</div>
              <div>• Email Addresses</div>
              <div>• Job Titles</div>
              <div>• Age</div>
              <div>• Password</div>
            </div>
            <br />
            <p>
              We also collect information from mobile devices for a better user
              experience, although these features are completely optional:
            </p>
            <br />
            <div className="space-y-3">
              <div>
                <strong>Location (GPS):</strong> Location data helps to create
                an accurate representation of your interests, and this can be
                used to bring more targeted and relevant ads to potential
                customers.
              </div>
              <div>
                <strong>Camera (Pictures):</strong> Granting camera permission
                allows the user to upload any picture straight from the
                platform, you can safely deny camera permissions for this
                platform.
              </div>
              <div>
                <strong>Photo Gallery (Pictures):</strong> Granting photo
                gallery access allows the user to upload any picture from their
                photo gallery, you can safely deny photo gallery access for this
                platform.
              </div>
            </div>
          </Section>

          <Section title="When Does BioYap Use End User Information from Third Parties?">
            <p>
              BioYap will collect End User Data necessary to provide the BioYap
              services to our customers. End users may voluntarily provide us
              with information they have made available on social media
              websites. If you provide us with any such information, we may
              collect publicly available information from the social media
              websites you have indicated. You can control how much of your
              information social media websites make public by visiting these
              websites and changing your privacy settings.
            </p>
          </Section>

          <Section title="When Does BioYap Use Customer Information from Third Parties?">
            <p>
              We receive some information from the third parties when you
              contact us. For example, when you submit your email address to us
              to show interest in becoming a BioYap customer, we receive
              information from a third party that provides automated fraud
              detection services to BioYap. We also occasionally collect
              information that is made publicly available on social media
              websites. You can control how much of your information social
              media websites make public by visiting these websites and changing
              your privacy settings.
            </p>
          </Section>

          <Section title="Do We Share the Information We Collect with Third Parties?">
            <p>
              We may share the information that we collect, both personal and
              non-personal, with third parties such as advertisers, contest
              sponsors, promotional and marketing partners, and others who
              provide our content or whose products or services we think may
              interest you. We may also share it with our current and future
              affiliated companies and business partners, and if we are involved
              in a merger, asset sale or other business reorganization, we may
              also share or transfer your personal and non-personal information
              to our successors-in-interest.
            </p>
            <br />
            <p>
              We may engage trusted third party service providers to perform
              functions and provide services to us, such as hosting and
              maintaining our servers and the website/app, database storage and
              management, e-mail management, storage marketing, credit card
              processing, customer service and fulfilling orders for products
              and services you may purchase through the website/app. We will
              likely share your personal information, and possibly some
              non-personal information, with these third parties to enable them
              to perform these services for us and for you.
            </p>
            <br />
            <p>
              We may share portions of our log file data, including IP
              addresses, for analytics purposes with third parties such as web
              analytics partners, application developers, and ad networks. If
              your IP address is shared, it may be used to estimate general
              location and other technographics such as connection speed,
              whether you have visited the website/app in a shared location, and
              type of the device used to visit the website/app. They may
              aggregate information about our advertising and what you see on
              the website/app and then provide auditing, research and reporting
              for us and our advertisers.
            </p>
            <br />
            <p>
              We may also disclose personal and non-personal information about
              you to government or law enforcement officials or private parties
              as we, in our sole discretion, believe necessary or appropriate in
              order to respond to claims, legal process (including subpoenas),
              to protect our rights and interests or those of a third party, the
              safety of the public or any person, to prevent or stop any
              illegal, unethical, or legally actionable activity, or to
              otherwise comply with applicable court orders, laws, rules and
              regulations.
            </p>
          </Section>

          <Section title="How Do We Use The Information We Collect?">
            <p>
              Any of the information we collect from you may be used in one of
              the following ways:
            </p>
            <br />
            <div className="space-y-2">
              <div>
                • To personalize your experience (your information helps us to
                better respond to your individual needs)
              </div>
              <div>
                • To improve our website/app (we continually strive to improve
                our website/app offerings based on the information and feedback
                we receive from you)
              </div>
              <div>
                • To improve customer service (your information helps us to more
                effectively respond to your customer service requests and
                support needs)
              </div>
              <div>• To process transactions</div>
              <div>
                • To administer a contest, promotion, survey or other site
                feature
              </div>
              <div>• To send periodic emails</div>
            </div>
          </Section>

          <Section title="How Do We Use Your Email Address?">
            <p>
              By submitting your email address on this website/app, you agree to
              receive emails from us. You can cancel your participation in any
              of these email lists at any time by clicking on the opt-out link
              or other unsubscribe option that is included in the respective
              email. We only send emails to people who have authorized us to
              contact them, either directly, or through a third party. We do not
              send unsolicited commercial emails, because we hate spam as much
              as you do. By submitting your email address, you also agree to
              allow us to use your email address for customer audience targeting
              on sites like Facebook, where we display custom advertising to
              specific people who have opted-in to receive communications from
              us. Email addresses submitted only through the order processing
              page will be used for the sole purpose of sending you information
              and updates pertaining to your order. If, however, you have
              provided the same email to us through another method, we may use
              it for any of the purposes stated in this Policy. Note: If at any
              time you would like to unsubscribe from receiving future emails,
              we include detailed unsubscribe instructions at the bottom of each
              email.
            </p>
          </Section>

          <Section title="How Long Do We Keep Your Information?">
            <p>
              We keep your information only so long as we need it to provide
              BioYap to you and fulfill the purposes described in this policy.
              This is also the case for anyone that we share your information
              with and who carries out services on our behalf. When we no longer
              need to use your information and there is no need for us to keep
              it to comply with our legal or regulatory obligations, we'll
              either remove it from our systems or depersonalize it so that we
              can't identify you.
            </p>
          </Section>

          <Section title="How Do We Protect Your Information?">
            <p>
              We implement a variety of security measures to maintain the safety
              of your personal information when you place an order or enter,
              submit, or access your personal information. We offer the use of a
              secure server. All supplied sensitive/credit information is
              transmitted via Secure Socket Layer (SSL) technology and then
              encrypted into our Payment gateway providers database only to be
              accessible by those authorized with special access rights to such
              systems, and are required to keep the information confidential.
              After a transaction, your private information (credit cards,
              social security numbers, financials, etc.) is never kept on file.
              We cannot, however, ensure or warrant the absolute security of any
              information you transmit to BioYap or guarantee that your
              information on the Service may not be accessed, disclosed,
              altered, or destroyed by a breach of any of our physical,
              technical, or managerial safeguards.
            </p>
          </Section>

          <Section title="Could My Information Be Transferred to Other Countries?">
            <p>
              BioYap is incorporated in United States of America. Information
              collected via our website/app, through direct interactions with
              you, or from use of our help services may be transferred from time
              to time to our offices or personnel, or to third parties, located
              throughout the world, and may be viewed and hosted anywhere in the
              world, including countries that may not have laws of general
              applicability regulating the use and transfer of such data. To the
              fullest extent allowed by applicable law, by using any of the
              above, you voluntarily consent to the trans-border transfer and
              hosting of such information.
            </p>
          </Section>

          <Section title="Is the information collected through the BioYap Service secure?">
            <p>
              We take precautions to protect the security of your information.
              We have physical, electronic, and managerial procedures to help
              safeguard, prevent unauthorized access, maintain data security,
              and correctly use your information. However, neither people nor
              security systems are foolproof, including encryption systems. In
              addition, people can commit intentional crimes, make mistakes or
              fail to follow policies. Therefore, while we use reasonable
              efforts to protect your personal information, we cannot guarantee
              its absolute security. If applicable law imposes any
              non-disclaimable duty to protect your personal information, you
              agree that intentional misconduct will be the standards used to
              measure our compliance with that duty.
            </p>
          </Section>

          <Section title="Can I update or correct my information?">
            <p>
              The rights you have to request updates or corrections to the
              information BioYap collects depend on your relationship with
              BioYap. Personnel may update or correct their information as
              detailed in our internal company employment policies.
            </p>
            <br />
            <p>
              Customers have the right to request the restriction of certain
              uses and disclosures of personally identifiable information as
              follows. You can contact us in order to (1) update or correct your
              personally identifiable information, (2) change your preferences
              with respect to communications and other information you receive
              from us, or (3) delete the personally identifiable information
              maintained about you on our systems (subject to the following
              paragraph), by cancelling your account. Such updates, corrections,
              changes and deletions will have no effect on other information
              that we maintain, or information that we have provided to third
              parties in accordance with this Privacy Policy prior to such
              update, correction, change or deletion. To protect your privacy
              and security, we may take reasonable steps (such as requesting a
              unique password) to verify your identity before granting you
              profile access or making corrections. You are responsible for
              maintaining the secrecy of your unique password and account
              information at all times.
            </p>
            <br />
            <p>
              You should be aware that it is not technologically possible to
              remove each and every record of the information you have provided
              to us from our system. The need to back up our systems to protect
              information from inadvertent loss means that a copy of your
              information may exist in a non-erasable form that will be
              difficult or impossible for us to locate. Promptly after receiving
              your request, all personal information stored in databases we
              actively use, and other readily searchable media will be updated,
              corrected, changed or deleted, as appropriate, as soon as and to
              the extent reasonably and technically practicable.
            </p>
            <br />
            <p>
              If you are an end user and wish to update, delete, or receive any
              information we have about you, you may do so by contacting the
              organization of which you are a customer.
            </p>
          </Section>

          <Section title="Personnel">
            <p>
              If you are a BioYap worker or applicant, we collect information
              you voluntarily provide to us. We use the information collected
              for Human Resources purposes in order to administer benefits to
              workers and screen applicants.
            </p>
            <br />
            <p>
              You may contact us in order to (1) update or correct your
              information, (2) change your preferences with respect to
              communications and other information you receive from us, or (3)
              receive a record of the information we have relating to you. Such
              updates, corrections, changes and deletions will have no effect on
              other information that we maintain, or information that we have
              provided to third parties in accordance with this Privacy Policy
              prior to such update, correction, change or deletion.
            </p>
          </Section>

          <Section title="Sale of Business">
            <p>
              We reserve the right to transfer information to a third party in
              the event of a sale, merger or other transfer of all or
              substantially all of the assets of BioYap or any of its Corporate
              Affiliates (as defined herein), or that portion of BioYap or any
              of its Corporate Affiliates to which the Service relates, or in
              the event that we discontinue our business or file a petition or
              have filed against us a petition in bankruptcy, reorganization or
              similar proceeding, provided that the third party agrees to adhere
              to the terms of this Privacy Policy.
            </p>
          </Section>

          <Section title="Affiliates">
            <p>
              We may disclose information (including personal information) about
              you to our Corporate Affiliates. For purposes of this Privacy
              Policy, "Corporate Affiliate" means any person or entity which
              directly or indirectly controls, is controlled by or is under
              common control with BioYap, whether by ownership or otherwise. Any
              information relating to you that we provide to our Corporate
              Affiliates will be treated by those Corporate Affiliates in
              accordance with the terms of this Privacy Policy.
            </p>
          </Section>

          <Section title="Governing Law">
            <p>
              This Privacy Policy is governed by the laws of United States of
              America without regard to its conflict of laws provision. You
              consent to the exclusive jurisdiction of the courts in connection
              with any action or dispute arising between the parties under or in
              connection with this Privacy Policy except for those individuals
              who may have rights to make claims under Privacy Shield, or the
              Swiss-US framework.
            </p>
            <br />
            <p>
              The laws of United States of America, excluding its conflicts of
              law rules, shall govern this Agreement and your use of the
              website/app. Your use of the website/app may also be subject to
              other local, state, national, or international laws.
            </p>
            <br />
            <p>
              By using BioYap or contacting us directly, you signify your
              acceptance of this Privacy Policy. If you do not agree to this
              Privacy Policy, you should not engage with our website/app, or use
              our services. Continued use of the website/app, direct engagement
              with us, or following the posting of changes to this Privacy
              Policy that do not significantly affect the use or disclosure of
              your personal information will mean that you accept those changes.
            </p>
          </Section>

          <Section title="Your Consent">
            <p>
              We've updated our Privacy Policy to provide you with complete
              transparency into what is being set when you visit our site and
              how it's being used. By using our BioYap, registering an account,
              or making a purchase, you hereby consent to our Privacy Policy and
              agree to its terms.
            </p>
          </Section>

          <Section title="Links to Other Websites">
            <p>
              This Privacy Policy applies only to the Services. The Services may
              contain links to other websites not operated or controlled by
              BioYap. We are not responsible for the content, accuracy or
              opinions expressed in such websites, and such websites are not
              investigated, monitored or checked for accuracy or completeness by
              us. Please remember that when you use a link to go from the
              Services to another website, our Privacy Policy is no longer in
              effect. Your browsing and interaction on any other website,
              including those that have a link on our platform, is subject to
              that website’s own rules and policies. Such third parties may use
              their own cookies or other methods to collect information about
              you.
            </p>
          </Section>

          <Section title="Cookies">
            <p>
              BioYap uses "Cookies" to identify the areas of our website/app
              that you have visited. A Cookie is a small piece of data stored on
              your computer or mobile device by your web browser. We use Cookies
              to enhance the performance and functionality of our website/app
              but are non-essential to their use. However, without these
              cookies, certain functionality like videos may become unavailable
              or you would be required to enter your login details every time
              you visit the website/app as we would not be able to remember that
              you had logged in previously. Most web browsers can be set to
              disable the use of Cookies. However, if you disable Cookies, you
              may not be able to access functionality on our website/app
              correctly or at all. We never place Personally Identifiable
              Information in Cookies.
            </p>
          </Section>

          <Section title="Blocking and disabling cookies and similar technologies">
            <p>
              Wherever you're located you may also set your browser to block
              cookies and similar technologies, but this action may block our
              essential cookies and prevent our website/app from functioning
              properly, and you may not be able to fully utilize all of its
              features and services. You should also be aware that you may also
              lose some saved information (e.g. saved login details, site
              preferences) if you block cookies on your browser. Different
              browsers make different controls available to you. Disabling a
              cookie or category of cookie does not delete the cookie from your
              browser, you will need to do this yourself from within your
              browser, you should visit your browser's help menu for more
              information.
            </p>
          </Section>

          <Section title="Payment Details">
            <p>
              In respect to any credit card or other payment processing details
              you have provided us, we commit that this confidential information
              will be stored in the most secure manner possible. servers.
            </p>
          </Section>

          <Section title="Kids' Privacy">
            <p>
              We do not address anyone under the age of 13. We do not knowingly
              collect personally identifiable information from anyone under the
              age of 13. If You are a parent or guardian and You are aware that
              Your child has provided Us with Personal Data, please contact Us.
              If We become aware that We have collected Personal Data from
              anyone under the age of 13 without verification of parental
              consent, We take steps to remove that information from Our
              servers.
            </p>
          </Section>

          <Section title="Changes To Our Privacy Policy">
            <p>
              We may change our Service and policies, and we may need to make
              changes to this Privacy Policy so that they accurately reflect our
              Service and policies. Unless otherwise required by law, we will
              notify you (for example, through our Service) before we make
              changes to this Privacy Policy and give you an opportunity to
              review them before they go into effect. Then, if you continue to
              use the Service, you will be bound by the updated Privacy Policy.
              If you do not want to agree to this or any updated Privacy Policy,
              you can delete your account.
            </p>
          </Section>

          <Section title="Third-Party Services">
            <p>
              We may display, include or make available third-party content
              (including data, information, applications and other products
              services) or provide links to third-party websites or services
              ("Third-Party Services").
            </p>
            <br />
            <p>
              You acknowledge and agree that BioYap shall not be responsible for
              any Third-Party Services, including their accuracy, completeness,
              timeliness, validity, copyright compliance, legality, decency,
              quality or any other aspect thereof. BioYap does not assume and
              shall not have any liability or responsibility to you or any other
              person or entity for any Third-Party Services.
            </p>
            <br />
            <p>
              Third-Party Services and links thereto are provided solely as a
              convenience to you and you access and use them entirely at your
              own risk and subject to such third parties' terms and conditions.
            </p>
          </Section>

          <Section title="Tracking Technologies">
            <Section title="Google Maps API">
              <p>
                Google Maps API is a robust tool that can be used to create a
                custom map, a searchable map, check-in functions, display live
                data synching with location, plan routes, or create a mashup
                just to name a few. Google Maps API may collect information from
                You and from Your Device for security purposes. Google Maps API
                collects information that is held in accordance with its Privacy
                Policy.
              </p>
            </Section>

            <Section title="Cookies">
              <p>
                We use Cookies to enhance the performance and functionality of
                our platform but are non-essential to their use. However,
                without these cookies, certain functionality like videos may
                become unavailable or you would be required to enter your login
                details every time you visit the platform as we would not be
                able to remember that you had logged in previously.
              </p>
            </Section>

            <Section title="Local Storage">
              <p>
                Local Storage sometimes known as DOM storage, provides web apps
                with methods and protocols for storing client-side data. Web
                storage supports persistent data storage, similar to cookies but
                with a greatly enhanced capacity and no information stored in
                the HTTP request header.
              </p>
            </Section>

            <Section title="Sessions">
              <p>
                We use "Sessions" to identify the areas of our platform that you
                have visited. A Session is a small piece of data stored on your
                computer or mobile device by your web browser.
              </p>
            </Section>
          </Section>

          <Section title="California Residents">
            <p>
              The California Consumer Privacy Act (CCPA) requires us to disclose
              categories of Personal Information we collect and how we use it,
              the categories of sources from whom we collect Personal
              Information, and the third parties with whom we share it, which we
              have explained above.
            </p>
            <br />
            <p>
              We are also required to communicate information about rights
              California residents have under California law. You may exercise
              the following rights:
            </p>
            <br />
            <div className="space-y-3">
              <div>
                <strong>Right to Know and Access:</strong> You may submit a
                verifiable request for information regarding the: (1) categories
                of Personal Information we collect, use, or share; (2) purposes
                for which categories of Personal Information are collected or
                used by us; (3) categories of sources from which we collect
                Personal Information; and (4) specific pieces of Personal
                Information we have collected about you.
              </div>
              <div>
                <strong>Right to Equal Service:</strong> We will not
                discriminate against you if you exercise your privacy rights.
              </div>
              <div>
                <strong>Right to Delete:</strong> You may submit a verifiable
                request to close your account and we will delete Personal
                Information about you that we have collected.
              </div>
              <div>
                Request that a business that sells a consumer's personal data,
                not sell the consumer's personal data.
              </div>
            </div>
            <br />
            <p>
              If you make a request, we have one month to respond to you. If you
              would like to exercise any of these rights, please contact us.
            </p>
            <br />
            <p>We do not sell the Personal Information of our users.</p>
            <br />
            <p>For more information about these rights, please contact us.</p>
          </Section>

          <Section title="California Online Privacy Protection Act (CalOPPA)">
            <p>
              CalOPPA requires us to disclose categories of Personal Information
              we collect and how we use it, the categories of sources from whom
              we collect Personal Information, and the third parties with whom
              we share it, which we have explained above.
            </p>
            <br />
            <p>CalOPPA users have the following rights:</p>
            <br />
            <div className="space-y-3">
              <div>
                <strong>Right to Know and Access:</strong> You may submit a
                verifiable request for information regarding the: (1) categories
                of Personal Information we collect, use, or share; (2) purposes
                for which categories of Personal Information are collected or
                used by us; (3) categories of sources from which we collect
                Personal Information; and (4) specific pieces of Personal
                Information we have collected about you.
              </div>
              <div>
                <strong>Right to Equal Service:</strong> We will not
                discriminate against you if you exercise your privacy rights.
              </div>
              <div>
                <strong>Right to Delete:</strong> You may submit a verifiable
                request to close your account and we will delete Personal
                Information about you that we have collected.
              </div>
              <div>
                <strong>Right to request:</strong> that a business that sells a
                consumer's personal data, not sell the consumer's personal data.
              </div>
            </div>
            <br />
            <p>
              If you make a request, we have one month to respond to you. If you
              would like to exercise any of these rights, please contact us.
            </p>
            <br />
            <p>We do not sell the Personal Information of our users.</p>
            <br />
            <p>For more information about these rights, please contact us.</p>
          </Section>

          <Section title="Contact Us">
            <p>
              Don't hesitate to contact us if you have any questions.
              <br />
              <br />
              Via Email:{" "}
              <a
                href="mailto:info@bioyap.com"
                className="text-blue-600 hover:underline"
              >
                info@bioyap.com
              </a>
              <br />
              Via this Link:{" "}
              <a
                href="https://www.bioyap.com"
                className="text-blue-600 hover:underline"
              >
                www.bioyap.com
              </a>
            </p>
          </Section>
        </div>
      </div>

      <Footer />
    </div>
  );
}

const Section = ({ title, children }) => {
  const { theme } = useContext(GlobalContext);

  return (
    <section>
      <h2
        className={`text-xl font-semibold mb-2 ${
          theme === "dark" ? "text-black" : "text-gray-800"
        }`}
      >
        {title}
      </h2>
      <div
        className={`leading-relaxed ${
          theme === "dark" ? "text-gray-400" : "text-black"
        }`}
      >
        {children}
      </div>
    </section>
  );
};
